/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElRadio: typeof import('element-plus/es')['ElRadio'];
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton'];
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    Home: typeof import('./src/components/Home.vue')['default'];
    I_Switch: typeof import('./src/components/global/I_Switch.vue')['default'];
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default'];
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default'];
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default'];
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default'];
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default'];
    Imenu: typeof import('./src/components/Imenu/index.vue')['default'];
    MaxLengthContainer: typeof import('./src/components/global/maxLengthContainer.vue')['default'];
    MaxLengthDiv: typeof import('./src/components/global/maxLengthDiv.vue')['default'];
    MenuInner: typeof import('./src/components/Imenu/MenuInner.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Switch: typeof import('./src/components/global/Switch.vue')['default'];
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default'];
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default'];
  }
}
